[package]
name = "watchdog"
version = "0.1.0"
edition = "2021"

[dependencies]
ignore = "0.4.23"
notify = { version = "7.0.0", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
