[extend]
extendables = [
  { extendable_type = "git", path = ".gitignore" },
]

[exclude]
files = [
  { path = ".git" },
]

[run]
command = "cargo"
args = [ "run" ]

[build]
command = "cargo"
args = [ "build" ]
