[extend]
extendables = [
  { extendable_type = "git", path = ".gitignore" },
]

[exclude]
files = [
  { path = ".git" },
]

[exec]
command = "cargo"
args = [ "run" ]

[exec_pre]
when = "always"
commands = [
  { command = "cargo", args = [ "build" ] },
]
